name: Generate Front Door Link and Post PR Comment
on:
  workflow_call:
      inputs:
        org-info:
          description: "Alias for the target scratch org"
          type: string
          required: true

jobs:
  generate-link:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Front Door Link
        id: generate_link
        run: |
          echo "ORG_INFO: ${{inputs.org-info}}"
          ORG_URL=$(${{inputs.org-info}} | jq -r '.result.instanceUrl')
          SESSION_ID=$(${{inputs.org-info}} | jq -r '.result.accessToken')
          FRONT_DOOR_LINK="${ORG_URL}/secur/frontdoor.jsp?sid=${SESSION_ID}"
          echo "::set-output name=front_door_link::${FRONT_DOOR_LINK}"
          echo "FRONT_DOOR_URL=${FRONT_DOOR_LINK}" >> $GITHUB_ENV

      - name: Post PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            if (!process.env.FRONT_DOOR_URL) {
              throw new Error("FRONT_DOOR_URL is not set");
            }
            const frontDoorUrl = process.env.FRONT_DOOR_URL;
            console.log(`Front Door URL: ${frontDoorUrl}`);
#            github.rest.issues.createComment({
#                issue_number: context.issue.number,
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                body: `The scratch org is active for 2 days. You can review the changes [here](${frontDoorUrl}).`
#            })
        env:
          FRONT_DOOR_URL: ${{ steps.generate_link.outputs.front_door_link }}
