name: Generate Front Door Link and Post PR Comment
on:
  workflow_call:
      inputs:
        target-org:
          description: "Alias for the target scratch org"
          type: string
          required: true

jobs:
  generate-link:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version

      - name: Populate auth file with DEVHUB_SFDX_URL secret
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL }}
          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt

      - name: Authenticate Dev Hub
        run: sf org login sfdx-url --sfdx-url-file ./DEVHUB_SFDX_URL.txt --alias devhub

      - name: Generate Front Door Link
        id: generate_link
        run: |
          sf org list
          sf org display --target-org ${{ inputs.target-org }}
               
          ORG_URL=$(sf org display --target-org ${{ inputs.target-org }} --json | jq -r '.result.instanceUrl')
          SESSION_ID=$(sf org display --target-org ${{ inputs.target-org }} --json | jq -r '.result.accessToken')
          FRONT_DOOR_LINK="${ORG_URL}/secur/frontdoor.jsp?sid=${SESSION_ID}"
          echo "::set-output name=front_door_link::${FRONT_DOOR_LINK}"
          echo "FRONT_DOOR_URL=${FRONT_DOOR_LINK}" >> $GITHUB_ENV

      - name: Post PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            if (!process.env.FRONT_DOOR_URL) {
              throw new Error("FRONT_DOOR_URL is not set");
            }
            const frontDoorUrl = process.env.FRONT_DOOR_URL;
            console.log(`Front Door URL: ${frontDoorUrl}`);
#            github.rest.issues.createComment({
#                issue_number: context.issue.number,
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                body: `The scratch org is active for 2 days. You can review the changes [here](${frontDoorUrl}).`
#            })
        env:
          FRONT_DOOR_URL: ${{ steps.generate_link.outputs.front_door_link }}
