name: Generate Front Door Link and Post PR Comment
on:
  workflow_call:
      inputs:
        target-org:
          description: "Alias for the target scratch org"
          type: string
          required: true
      secrets:
        github-token:
          description: "GitHub token for authentication"
          required: true

jobs:
  generate-link:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version

      - name: Generate Front Door Link
        id: generate_link
        run: |
          ORG_URL=$(sf org display --target-org ${{ inputs.target-org }} --json | jq -r '.result.instanceUrl')
          SESSION_ID=$(sf org display --target-org ${{ inputs.target-org }} --json | jq -r '.result.accessToken')
          FRONT_DOOR_LINK="${ORG_URL}/secur/frontdoor.jsp?sid=${SESSION_ID}"
          echo "::set-output name=front_door_link::${FRONT_DOOR_LINK}"

      - name: Post PR Comment
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENT="#### Salesforce Scratch Org Front Door Link\n${{ steps.generate_link.outputs.front_door_link }}"
          PAYLOAD=$(echo "${COMMENT}" | jq -R --slurp '{body: .}')
          COMMENTS_URL=$(jq -r .pull_request.comments_url < "$GITHUB_EVENT_PATH")

          echo "${PAYLOAD}" | curl -s -S -H "Authorization: token ${{ secrets.github-token }}" --header "Content-Type: application/json" --data @- "${COMMENTS_URL}" > /dev/null
